### PR TITLE
Add: New Weather Icons.

### PR DESCRIPTION
**Pull request by KevDoy**
Add: New Weather icons

### CODE REVIEW

**Comment by ghost** [comment]
Very nice!

I'll let the other developers chime in, but you may want to change the 
commit
message to "Add: New weather icons." to follow the official commit 
style.

Thanks.

**Comment by KevDoy** [comment]
Thank you!

Based on their feedback, I may make a few more

**Comment by ghost** [comment]
@KevDoy, I will merge this in, but first, would you mind changing the commit message to: "Add: New weather icons."? I see that you changed the PR comment to read as such, but it'd be great if you could amend the actual commit message to be that as well.

Thanks!

**Comment by KevDoy** [comment]
@sgtbigman oh sorry about that. Thank you!

**Pull request merged**
