### PR TITLE
Add Swedish (Sweden)/sv_SE language

### PR DESCRIPTION
**Pull request by Newbytee**
~~I've had some issues with this.~~

 1. ~~I don't understand what "Click at the title bar to raise the window" is supposed to mean.~~
 2. ~~I added the new language here and there in the code, but it shows up as a blank entry that goes back to en_GB when selected in language settings menu. What might I be missing?~~

### CODE REVIEW

**Comment by Alberth289346** [comment]
> I don't understand what "Click at the title bar to raise the window" is supposed to mean.

"Click at the title bar" is literally clicking at the title bar of a window, the top part that says what the window is about,

When you have 2 opened windows partly overlapping, one of them is at the front (fully visible), and one of them is at the back (partly visible). "Raising a window" mean putting a window at the front.
If you do that with the front window nothing changes, if you do that with the other window, it goes to the front (becomes fully visible), and all other windows hide (partly) behind them.

**Comment by Alberth289346** [comment]
As for not working, likely more needs to change, but I can't get that done today, will have a look tomorrow.

**Comment by Newbytee** [comment]
> > I don't understand what "Click at the title bar to raise the window" is supposed to mean.

> When you have 2 opened windows partly overlapping, one of them is at the front (fully visible), and one of them is at the back (partly visible). "Raising a window" mean putting a window at the front.

Thanks, that's the part I was confused about.

**Comment by Alberth289346** [comment]
Things seem to be working here:
Screenshot from 2021-01-24 10-53-32

Font is a bit silly, I got the wrong TTF file :)
You probably didn't re-generate the RCD files after adding the language to the source code.

Could you change the "wip" commit message please?
Don't know if you want to change that last string, but feel free to.

**Comment by Newbytee** [comment]
> Things seem to be working here

Great!

> You probably didn't re-generate the RCD files after adding the language to the source code.

How would I go about doing that?

> Could you change the "wip" commit message please?

Yeah, I'll rebase before marking it as ready.

> Don't know if you want to change that last string, but feel free to.

Which one?

**Comment by Newbytee** [comment]
Never mind, managed to regenerate the RCD files by doing a clean build.

Better solution:

    $ make rcd

**Comment by Newbytee** [comment]
I'll mark as draft again as I want to update some translations now that I see them in the game

**Pull request merged**
