### PR TITLE
german translation update

### PR DESCRIPTION
**Pull request by vatriani**
I've done a translation update. Also the currency is changed to euro and the decimal/thousand seperator is fixed to german ones.

### CODE REVIEW

**Comment by vatriani** [comment]
sorry ive overlooked 6 translations

**Comment by ghost** [comment]
This looks good. Would you be able to 'fixup' commit c207650 into 976c306?

Thanks for updating these translations!

**Comment by vatriani** [comment]
c207650 and 976c306 merged together in f766491

**Comment by ghost** [comment]
Excellent. Looks good to me.

**Pull request merged**
